# Makefile.deps created Fri Apr  9 19:18:00 PDT 2021
ubigint.o: ubigint.cpp debug.h relops.h ubigint.h
bigint.o: bigint.cpp bigint.h debug.h relops.h ubigint.h
libfns.o: libfns.cpp libfns.h bigint.h debug.h relops.h ubigint.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp bigint.h debug.h relops.h ubigint.h iterstack.h libfns.h \
  scanner.h util.h
